name: turtle_move # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Test for custom turtlebot3 move on ros2 # 79 char long summary
description: |
  This is my-snap's description.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  ros-demos:
    plugin: colcon
    source: https://github.com/Nanashi1Kuro/Robosim.git
    source-branch: galactic
    source-subdir: turtlebot3_simulations
    stage-packages: [ros-galactic-ros2launch]

apps:
  ros2-move:
    command: opt/ros/galactic/bin/ros2 launch like_a_rumba_robot runpy.launch.py
    plugs: [network, network-bind]
    extensions: [ros2-galactic]
